// <auto-generated />
using System;
using ExpirationTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExpirationTracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260521203003_NormalizeDriverExpiryAndAddTrucks")]
    partial class NormalizeDriverExpiryAndAddTrucks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExpirationTracker.Models.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DriverNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Drivers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DriverName = "Buck",
                            DriverNumber = "0815"
                        },
                        new
                        {
                            Id = 2,
                            DriverName = "Darron",
                            DriverNumber = "7065"
                        },
                        new
                        {
                            Id = 3,
                            DriverName = "Jerome",
                            DriverNumber = "1190"
                        },
                        new
                        {
                            Id = 4,
                            DriverName = "Chris G",
                            DriverNumber = "1960"
                        },
                        new
                        {
                            Id = 5,
                            DriverName = "Jeff",
                            DriverNumber = "4366"
                        },
                        new
                        {
                            Id = 6,
                            DriverName = "Q",
                            DriverNumber = "9271"
                        },
                        new
                        {
                            Id = 7,
                            DriverName = "Freddy",
                            DriverNumber = "4057"
                        });
                });

            modelBuilder.Entity("ExpirationTracker.Models.ExpiryDate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<string>("ExpirationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ExpiryOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("TruckId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("TruckId");

                    b.ToTable("ExpiryDates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DriverId = 1,
                            ExpirationType = "DOT Inspection",
                            ExpiryOn = new DateTime(2026, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TruckId = 1
                        },
                        new
                        {
                            Id = 2,
                            DriverId = 1,
                            ExpirationType = "Truck Tag",
                            ExpiryOn = new DateTime(2026, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TruckId = 1
                        },
                        new
                        {
                            Id = 3,
                            DriverId = 1,
                            ExpirationType = "IRP",
                            ExpiryOn = new DateTime(2026, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TruckId = 1
                        },
                        new
                        {
                            Id = 4,
                            DriverId = 1,
                            ExpirationType = "Physical",
                            ExpiryOn = new DateTime(2026, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TruckId = 1
                        },
                        new
                        {
                            Id = 5,
                            DriverId = 2,
                            ExpirationType = "DOT Inspection",
                            ExpiryOn = new DateTime(2027, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TruckId = 2
                        },
                        new
                        {
                            Id = 6,
                            DriverId = 3,
                            ExpirationType = "DOT Inspection",
                            ExpiryOn = new DateTime(2026, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TruckId = 3
                        },
                        new
                        {
                            Id = 7,
                            DriverId = 3,
                            ExpirationType = "Truck Tag",
                            ExpiryOn = new DateTime(2027, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TruckId = 3
                        },
                        new
                        {
                            Id = 8,
                            DriverId = 3,
                            ExpirationType = "IRP",
                            ExpiryOn = new DateTime(2027, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TruckId = 3
                        },
                        new
                        {
                            Id = 9,
                            DriverId = 3,
                            ExpirationType = "Physical",
                            ExpiryOn = new DateTime(2027, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TruckId = 3
                        },
                        new
                        {
                            Id = 10,
                            DriverId = 3,
                            ExpirationType = "DOT Inspection",
                            ExpiryOn = new DateTime(2027, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TruckId = 4
                        },
                        new
                        {
                            Id = 11,
                            DriverId = 3,
                            ExpirationType = "Truck Tag",
                            ExpiryOn = new DateTime(2027, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TruckId = 4
                        },
                        new
                        {
                            Id = 12,
                            DriverId = 3,
                            ExpirationType = "IRP",
                            ExpiryOn = new DateTime(2027, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TruckId = 4
                        },
                        new
                        {
                            Id = 13,
                            DriverId = 3,
                            ExpirationType = "Physical",
                            ExpiryOn = new DateTime(2027, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TruckId = 4
                        },
                        new
                        {
                            Id = 14,
                            DriverId = 4,
                            ExpirationType = "DOT Inspection",
                            ExpiryOn = new DateTime(2026, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TruckId = 5
                        },
                        new
                        {
                            Id = 15,
                            DriverId = 4,
                            ExpirationType = "Truck Tag",
                            ExpiryOn = new DateTime(2026, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TruckId = 5
                        },
                        new
                        {
                            Id = 16,
                            DriverId = 4,
                            ExpirationType = "IRP",
                            ExpiryOn = new DateTime(2026, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TruckId = 5
                        },
                        new
                        {
                            Id = 17,
                            DriverId = 4,
                            ExpirationType = "Physical",
                            ExpiryOn = new DateTime(2026, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TruckId = 5
                        },
                        new
                        {
                            Id = 18,
                            DriverId = 4,
                            ExpirationType = "DOT Inspection",
                            ExpiryOn = new DateTime(2026, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TruckId = 6
                        },
                        new
                        {
                            Id = 19,
                            DriverId = 4,
                            ExpirationType = "Truck Tag",
                            ExpiryOn = new DateTime(2026, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TruckId = 6
                        },
                        new
                        {
                            Id = 20,
                            DriverId = 4,
                            ExpirationType = "IRP",
                            ExpiryOn = new DateTime(2026, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TruckId = 6
                        },
                        new
                        {
                            Id = 21,
                            DriverId = 4,
                            ExpirationType = "Physical",
                            ExpiryOn = new DateTime(2026, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TruckId = 6
                        },
                        new
                        {
                            Id = 22,
                            DriverId = 5,
                            ExpirationType = "DOT Inspection",
                            ExpiryOn = new DateTime(2026, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TruckId = 7
                        },
                        new
                        {
                            Id = 23,
                            DriverId = 5,
                            ExpirationType = "Truck Tag",
                            ExpiryOn = new DateTime(2027, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TruckId = 7
                        },
                        new
                        {
                            Id = 24,
                            DriverId = 5,
                            ExpirationType = "IRP",
                            ExpiryOn = new DateTime(2027, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TruckId = 7
                        },
                        new
                        {
                            Id = 25,
                            DriverId = 5,
                            ExpirationType = "Physical",
                            ExpiryOn = new DateTime(2027, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TruckId = 7
                        },
                        new
                        {
                            Id = 26,
                            DriverId = 6,
                            ExpirationType = "DOT Inspection",
                            ExpiryOn = new DateTime(2026, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TruckId = 8
                        },
                        new
                        {
                            Id = 27,
                            DriverId = 6,
                            ExpirationType = "Truck Tag",
                            ExpiryOn = new DateTime(2026, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TruckId = 8
                        },
                        new
                        {
                            Id = 28,
                            DriverId = 6,
                            ExpirationType = "IRP",
                            ExpiryOn = new DateTime(2026, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TruckId = 8
                        },
                        new
                        {
                            Id = 29,
                            DriverId = 6,
                            ExpirationType = "Physical",
                            ExpiryOn = new DateTime(2026, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TruckId = 8
                        },
                        new
                        {
                            Id = 30,
                            DriverId = 7,
                            ExpirationType = "DOT Inspection",
                            ExpiryOn = new DateTime(2027, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TruckId = 9
                        },
                        new
                        {
                            Id = 31,
                            DriverId = 7,
                            ExpirationType = "Truck Tag",
                            ExpiryOn = new DateTime(2026, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TruckId = 9
                        },
                        new
                        {
                            Id = 32,
                            DriverId = 7,
                            ExpirationType = "IRP",
                            ExpiryOn = new DateTime(2026, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TruckId = 9
                        },
                        new
                        {
                            Id = 33,
                            DriverId = 7,
                            ExpirationType = "Physical",
                            ExpiryOn = new DateTime(2026, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TruckId = 9
                        });
                });

            modelBuilder.Entity("ExpirationTracker.Models.Trailer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AnnualInspExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("AssignedTo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("HasHeadboard")
                        .HasColumnType("bit");

                    b.Property<string>("Make")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("TagExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("TagNotes")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TagNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TrailerNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Vin")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Year")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Trailers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnnualInspExpiry = new DateTime(2027, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AssignedTo = "Buck",
                            HasHeadboard = false,
                            Make = "Transcraft",
                            Model = "554C Eagle II",
                            TagExpiry = new DateTime(2026, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TagNumber = "1A0BUM2",
                            TrailerNumber = "7432",
                            Vin = "1TTF482CXL3196914",
                            Year = "2020"
                        },
                        new
                        {
                            Id = 2,
                            AnnualInspExpiry = new DateTime(2027, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AssignedTo = "Darron",
                            HasHeadboard = true,
                            Make = "Transcraft",
                            Model = "554C Eagle II",
                            TagExpiry = new DateTime(2026, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TagNumber = "1A0BUHX",
                            TrailerNumber = "5863",
                            Vin = "1TTF482C3L3196866",
                            Year = "2020"
                        },
                        new
                        {
                            Id = 3,
                            AnnualInspExpiry = new DateTime(2027, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AssignedTo = "Jerome",
                            HasHeadboard = false,
                            Make = "Transcraft",
                            Model = "554C Eagle II",
                            TagExpiry = new DateTime(2026, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TagNumber = "1A0BUM1",
                            TrailerNumber = "5860",
                            Vin = "1TTF482CXJ3060408",
                            Year = "2018"
                        },
                        new
                        {
                            Id = 4,
                            AnnualInspExpiry = new DateTime(2026, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AssignedTo = "Chris G",
                            HasHeadboard = false,
                            Make = "Transcraft",
                            Model = "48' Flatbed",
                            TagExpiry = new DateTime(2026, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TagNumber = "62AOMBH",
                            TrailerNumber = "943",
                            Vin = "1TTF482C3F3895967",
                            Year = "2015"
                        },
                        new
                        {
                            Id = 5,
                            AnnualInspExpiry = new DateTime(2026, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AssignedTo = "Jeff",
                            HasHeadboard = false,
                            Make = "Transcraft",
                            Model = "554C Eagle II",
                            TagExpiry = new DateTime(2026, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TagNumber = "1AOBUHY",
                            TrailerNumber = "5862",
                            Vin = "1TTF482C0K3142116",
                            Year = "2019"
                        },
                        new
                        {
                            Id = 6,
                            AnnualInspExpiry = new DateTime(2027, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AssignedTo = "Q",
                            HasHeadboard = true,
                            Make = "Transcraft",
                            Model = "554C Eagle II",
                            TagNotes = "Perm",
                            TagNumber = "A004585",
                            TrailerNumber = "5854",
                            Vin = "1TTF482C1H3027890",
                            Year = "2017"
                        },
                        new
                        {
                            Id = 7,
                            AnnualInspExpiry = new DateTime(2027, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AssignedTo = "Freddy",
                            HasHeadboard = true,
                            Make = "Transcraft",
                            Model = "48' Flatbed",
                            TagExpiry = new DateTime(2026, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TagNumber = "1A0BUHE",
                            TrailerNumber = "7201",
                            Vin = "1TTF482C5C3576713",
                            Year = "2012"
                        },
                        new
                        {
                            Id = 8,
                            AnnualInspExpiry = new DateTime(2026, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AssignedTo = "Rented",
                            HasHeadboard = false,
                            Make = "Transcraft",
                            Model = "554C Eagle II",
                            TagExpiry = new DateTime(2026, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TagNumber = "1A0BUM0",
                            TrailerNumber = "5861",
                            Vin = "1TTF482C4K3133001",
                            Year = "2019"
                        },
                        new
                        {
                            Id = 9,
                            AnnualInspExpiry = new DateTime(2027, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HasHeadboard = false,
                            Make = "Transcraft",
                            Model = "554C Eagle II",
                            TagNotes = "Perm",
                            TagNumber = "A138145",
                            TrailerNumber = "60852",
                            Vin = "1TTF482C2F3873328",
                            Year = "2015"
                        });
                });

            modelBuilder.Entity("ExpirationTracker.Models.Truck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Make")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ModelYear")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("TruckNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Vin")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Trucks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TruckNo = "5800"
                        },
                        new
                        {
                            Id = 2,
                            TruckNo = "5003"
                        },
                        new
                        {
                            Id = 3,
                            TruckNo = "3439"
                        },
                        new
                        {
                            Id = 4,
                            TruckNo = "3440"
                        },
                        new
                        {
                            Id = 5,
                            TruckNo = "5737"
                        },
                        new
                        {
                            Id = 6,
                            TruckNo = "5736"
                        },
                        new
                        {
                            Id = 7,
                            TruckNo = "6195"
                        },
                        new
                        {
                            Id = 8,
                            TruckNo = "6181"
                        },
                        new
                        {
                            Id = 9,
                            TruckNo = "455"
                        });
                });

            modelBuilder.Entity("ExpirationTracker.Models.ExpiryDate", b =>
                {
                    b.HasOne("ExpirationTracker.Models.Driver", "Driver")
                        .WithMany("ExpiryDates")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ExpirationTracker.Models.Truck", "Truck")
                        .WithMany("ExpiryDates")
                        .HasForeignKey("TruckId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Truck");
                });

            modelBuilder.Entity("ExpirationTracker.Models.Driver", b =>
                {
                    b.Navigation("ExpiryDates");
                });

            modelBuilder.Entity("ExpirationTracker.Models.Truck", b =>
                {
                    b.Navigation("ExpiryDates");
                });
#pragma warning restore 612, 618
        }
    }
}
