// <auto-generated />
using System;
using ExpirationTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExpirationTracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260523163946_AddTruckDocuments")]
    partial class AddTruckDocuments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExpirationTracker.Models.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DriverNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("LicenseExpiry")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PhysicalExpiry")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Drivers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DriverName = "Buck",
                            DriverNumber = "0815",
                            PhysicalExpiry = new DateTime(2026, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            DriverName = "Darron",
                            DriverNumber = "7065"
                        },
                        new
                        {
                            Id = 3,
                            DriverName = "Jerome",
                            DriverNumber = "1190",
                            PhysicalExpiry = new DateTime(2027, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            DriverName = "Chris G",
                            DriverNumber = "1960",
                            PhysicalExpiry = new DateTime(2026, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            DriverName = "Jeff",
                            DriverNumber = "4366",
                            PhysicalExpiry = new DateTime(2027, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            DriverName = "Q",
                            DriverNumber = "9271",
                            PhysicalExpiry = new DateTime(2026, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            DriverName = "Freddy",
                            DriverNumber = "4057",
                            PhysicalExpiry = new DateTime(2026, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("ExpirationTracker.Models.DriverDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<string>("ExpirationType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DriverId", "ExpirationType")
                        .IsUnique();

                    b.ToTable("DriverDocuments");
                });

            modelBuilder.Entity("ExpirationTracker.Models.Trailer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AnnualInspExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("AssignedTo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("HasHeadboard")
                        .HasColumnType("bit");

                    b.Property<string>("Make")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("TagExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("TagNotes")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TagNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TrailerNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Vin")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Year")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Trailers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnnualInspExpiry = new DateTime(2027, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AssignedTo = "Buck",
                            HasHeadboard = false,
                            Make = "Transcraft",
                            Model = "554C Eagle II",
                            TagExpiry = new DateTime(2026, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TagNumber = "1A0BUM2",
                            TrailerNumber = "7432",
                            Vin = "1TTF482CXL3196914",
                            Year = "2020"
                        },
                        new
                        {
                            Id = 2,
                            AnnualInspExpiry = new DateTime(2027, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AssignedTo = "Darron",
                            HasHeadboard = true,
                            Make = "Transcraft",
                            Model = "554C Eagle II",
                            TagExpiry = new DateTime(2026, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TagNumber = "1A0BUHX",
                            TrailerNumber = "5863",
                            Vin = "1TTF482C3L3196866",
                            Year = "2020"
                        },
                        new
                        {
                            Id = 3,
                            AnnualInspExpiry = new DateTime(2027, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AssignedTo = "Jerome",
                            HasHeadboard = false,
                            Make = "Transcraft",
                            Model = "554C Eagle II",
                            TagExpiry = new DateTime(2026, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TagNumber = "1A0BUM1",
                            TrailerNumber = "5860",
                            Vin = "1TTF482CXJ3060408",
                            Year = "2018"
                        },
                        new
                        {
                            Id = 4,
                            AnnualInspExpiry = new DateTime(2026, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AssignedTo = "Chris G",
                            HasHeadboard = false,
                            Make = "Transcraft",
                            Model = "48' Flatbed",
                            TagExpiry = new DateTime(2026, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TagNumber = "62AOMBH",
                            TrailerNumber = "943",
                            Vin = "1TTF482C3F3895967",
                            Year = "2015"
                        },
                        new
                        {
                            Id = 5,
                            AnnualInspExpiry = new DateTime(2026, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AssignedTo = "Jeff",
                            HasHeadboard = false,
                            Make = "Transcraft",
                            Model = "554C Eagle II",
                            TagExpiry = new DateTime(2026, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TagNumber = "1AOBUHY",
                            TrailerNumber = "5862",
                            Vin = "1TTF482C0K3142116",
                            Year = "2019"
                        },
                        new
                        {
                            Id = 6,
                            AnnualInspExpiry = new DateTime(2027, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AssignedTo = "Q",
                            HasHeadboard = true,
                            Make = "Transcraft",
                            Model = "554C Eagle II",
                            TagNotes = "Perm",
                            TagNumber = "A004585",
                            TrailerNumber = "5854",
                            Vin = "1TTF482C1H3027890",
                            Year = "2017"
                        },
                        new
                        {
                            Id = 7,
                            AnnualInspExpiry = new DateTime(2027, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AssignedTo = "Freddy",
                            HasHeadboard = true,
                            Make = "Transcraft",
                            Model = "48' Flatbed",
                            TagExpiry = new DateTime(2026, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TagNumber = "1A0BUHE",
                            TrailerNumber = "7201",
                            Vin = "1TTF482C5C3576713",
                            Year = "2012"
                        },
                        new
                        {
                            Id = 8,
                            AnnualInspExpiry = new DateTime(2026, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AssignedTo = "Rented",
                            HasHeadboard = false,
                            Make = "Transcraft",
                            Model = "554C Eagle II",
                            TagExpiry = new DateTime(2026, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TagNumber = "1A0BUM0",
                            TrailerNumber = "5861",
                            Vin = "1TTF482C4K3133001",
                            Year = "2019"
                        },
                        new
                        {
                            Id = 9,
                            AnnualInspExpiry = new DateTime(2027, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HasHeadboard = false,
                            Make = "Transcraft",
                            Model = "554C Eagle II",
                            TagNotes = "Perm",
                            TagNumber = "A138145",
                            TrailerNumber = "60852",
                            Vin = "1TTF482C2F3873328",
                            Year = "2015"
                        });
                });

            modelBuilder.Entity("ExpirationTracker.Models.TrailerDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ExpirationType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<int>("TrailerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TrailerId", "ExpirationType")
                        .IsUnique();

                    b.ToTable("TrailerDocuments");
                });

            modelBuilder.Entity("ExpirationTracker.Models.Truck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DotInspectionExpiry")
                        .HasColumnType("datetime2");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("IrpExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ModelYear")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<int>("TruckMakeId")
                        .HasColumnType("int");

                    b.Property<string>("TruckNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("TruckTagExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Vin")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("TruckMakeId");

                    b.ToTable("Trucks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DotInspectionExpiry = new DateTime(2026, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriverId = 1,
                            IrpExpiry = new DateTime(2026, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TruckMakeId = 1,
                            TruckNo = "5800",
                            TruckTagExpiry = new DateTime(2026, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            DotInspectionExpiry = new DateTime(2027, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriverId = 2,
                            TruckMakeId = 1,
                            TruckNo = "5003"
                        },
                        new
                        {
                            Id = 3,
                            DotInspectionExpiry = new DateTime(2026, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriverId = 3,
                            IrpExpiry = new DateTime(2027, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TruckMakeId = 1,
                            TruckNo = "3439",
                            TruckTagExpiry = new DateTime(2027, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            DotInspectionExpiry = new DateTime(2027, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriverId = 3,
                            IrpExpiry = new DateTime(2027, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TruckMakeId = 1,
                            TruckNo = "3440",
                            TruckTagExpiry = new DateTime(2027, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            DotInspectionExpiry = new DateTime(2026, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriverId = 4,
                            IrpExpiry = new DateTime(2026, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TruckMakeId = 1,
                            TruckNo = "5737",
                            TruckTagExpiry = new DateTime(2026, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            DotInspectionExpiry = new DateTime(2026, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriverId = 4,
                            IrpExpiry = new DateTime(2026, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TruckMakeId = 1,
                            TruckNo = "5736",
                            TruckTagExpiry = new DateTime(2026, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            DotInspectionExpiry = new DateTime(2026, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriverId = 5,
                            IrpExpiry = new DateTime(2027, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TruckMakeId = 1,
                            TruckNo = "6195",
                            TruckTagExpiry = new DateTime(2027, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            DotInspectionExpiry = new DateTime(2026, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriverId = 6,
                            IrpExpiry = new DateTime(2026, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TruckMakeId = 1,
                            TruckNo = "6181",
                            TruckTagExpiry = new DateTime(2026, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            DotInspectionExpiry = new DateTime(2027, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriverId = 7,
                            IrpExpiry = new DateTime(2026, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TruckMakeId = 1,
                            TruckNo = "455",
                            TruckTagExpiry = new DateTime(2026, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("ExpirationTracker.Models.TruckDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ExpirationType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<int>("TruckId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TruckId", "ExpirationType")
                        .IsUnique();

                    b.ToTable("TruckDocuments");
                });

            modelBuilder.Entity("ExpirationTracker.Models.TruckMake", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TruckMakes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Freightliner"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Peterbilt"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Volvo"
                        });
                });

            modelBuilder.Entity("ExpirationTracker.Models.DriverDocument", b =>
                {
                    b.HasOne("ExpirationTracker.Models.Driver", "Driver")
                        .WithMany("Documents")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("ExpirationTracker.Models.TrailerDocument", b =>
                {
                    b.HasOne("ExpirationTracker.Models.Trailer", "Trailer")
                        .WithMany("Documents")
                        .HasForeignKey("TrailerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trailer");
                });

            modelBuilder.Entity("ExpirationTracker.Models.Truck", b =>
                {
                    b.HasOne("ExpirationTracker.Models.Driver", "Driver")
                        .WithMany("Trucks")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ExpirationTracker.Models.TruckMake", "TruckMake")
                        .WithMany("Trucks")
                        .HasForeignKey("TruckMakeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("TruckMake");
                });

            modelBuilder.Entity("ExpirationTracker.Models.TruckDocument", b =>
                {
                    b.HasOne("ExpirationTracker.Models.Truck", "Truck")
                        .WithMany("Documents")
                        .HasForeignKey("TruckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Truck");
                });

            modelBuilder.Entity("ExpirationTracker.Models.Driver", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Trucks");
                });

            modelBuilder.Entity("ExpirationTracker.Models.Trailer", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("ExpirationTracker.Models.Truck", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("ExpirationTracker.Models.TruckMake", b =>
                {
                    b.Navigation("Trucks");
                });
#pragma warning restore 612, 618
        }
    }
}
